# Generated by Django 4.2.4 on 2023-08-08 08:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("userportal", "0002_remove_userdetails_is_superuser"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userdetails",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="userdetails",
            name="last_name",
        ),
    ]
