# Generated by Django 4.2.4 on 2023-08-08 08:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("userportal", "0004_userdetails_date_joined_userdetails_first_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userdetails",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="userdetails",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="userdetails",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="userdetails",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="userdetails",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="userdetails",
            name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="userdetails",
            name="last_login",
        ),
        migrations.RemoveField(
            model_name="userdetails",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="userdetails",
            name="user_permissions",
        ),
    ]
