# Generated by Django 4.2.4 on 2023-08-08 09:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userportal", "0005_remove_userdetails_date_joined_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdetails",
            name="phonenumber",
            field=models.CharField(default=1, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
